name: HL_Beta
favicon: null
layout_spectrum: 0.74206
typography_spectrum: 0.99286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
